insert into `Item`(`name`,`price`,`type`,`description`,id)
values
('Vegetable Pakora','3.00','Veg','Starters',default),
('Vegetable Samosa','3.00','Veg','Starters',default),
('Onion Bhaji ','3.00','Veg','Starters',default),
('Potato and Mushroom Chaat','3.00','Veg','Starters',default),
('Mushroom Garlic Fry','3.00','Veg','Starters',default),
('Chicken Tikka','4.00','Non-Veg','Starters',default),
('Tandoori Chicken','4.00','Non-Veg','Starters',default),
('Chicken Garlic Fry','4.00','Non-Veg','Starters',default),
('Chicken Tikka on Puree','4.00','Non-Veg','Starters',default),
('Lamb Tikka','4.00','Non-Veg','Starters',default),
('Tandoori King Prawn','6.95','Non-Veg','SeaFood',default),
('King Prawn Rosun','5.95','Non-Veg','SeaFood',default),
('King Prawn on Puree','5.95','Non-Veg','SeaFood',default),
('Prawn Bhuna on Puree','3.95','Non-Veg','SeaFood',default),
('Prawn Cocktail','3.95','Non-Veg','SeaFood',default),
('Chi/Lam Sashlik Chi','9.95','Non-Veg','Tandoori Specials',default),
('Tandoori Deluxe','12.95','Non-Veg','Tandoori Specials',default),
('Tandoori Chicken Main','9.95','Non-Veg','Tandoori Specials',default),
('Chicken Tikka','7.95','Non-Veg','Tandoori Specials',default),
('Lamb Tikka','9.95','Non-Veg','Tandoori Specials',default),
('Bombay Aloo ','6.50','Veg','Vegetable Dishes',default),
('Mushroom Bhaji ','6.50','Veg','Vegetable Dishes',default),
('Saag Dall','6.50','Veg','Vegetable Dishes',default),
('Mattor Paneer','6.50','Veg','Vegetable Dishes',default),
('Vegetable Roshun','6.50','Veg','Vegetable Dishes',default),
('Boiled Rice','2.50','Veg','Side Orders - Rice',default),
('Keema Pilau Rice','3.50','Non-Veg','Side Orders - Rice',default),
('Mushroom Rice','3.20','Veg','Side Orders - Rice',default),
('Garlic Naan','3.00','Veg','Side Orders - Bread',default),
('Stuffed Naan','3.50','Veg','Side Orders - Bread',default),
('Chapati','1.00','Veg','Side Orders - Bread',default),
('Green Salad','2.00','Veg','Side Orders - Sundries',default),
('Spice Popadum','0.80','Veg','Side Orders - Sundries',default),
('Chutney','0.70','Veg','Side Orders - Sundries',default),
('Ras Malai','2.95','Veg','Dessert',default),
('Ice Cream','2.95','Veg','Dessert',default),
('Gulab Jamun','2.95','Veg','Dessert',default),
('Kulfi','2.95','Veg','Dessert',default),
('Kheer','2.95','Veg','Dessert',default);